# vim: set syntax=dockerfile:
FROM gcr.io/kubeflow-images-public/tensorflow-2.0.0a-notebook-cpu:v0.5.0
RUN conda install -y pytorch torchvision -c pytorch

RUN pip install --no-cache-dir \
    cmake

RUN pip install --no-cache-dir \
    dill==0.3.0 \
    pandas==0.24.2 \
    matplotlib==3.1.1 \
    scipy==1.3.0 \
    numpy==1.16.4 \
    plotly==4.0.0 \
    recordclass==0.11.1 \
    fastai==1.0.57
